In [2]:
import numpy as np


In [21]:
a = np.arange(15)
def print_np_array(nparr):
    print("---------nparr:------------")
    print(nparr)
    print("size:", nparr.size)
    print("shape:", nparr.shape)
    print("ndim:", nparr.ndim)
    print("dtype:", nparr.dtype)
    print("data:", nparr.data)
    print("itemsize:", nparr.itemsize)
print_np_array(a)
print_np_array(a.reshape((3,5)))

---------nparr:------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
size: 15
shape: (15,)
ndim: 1
dtype: int32
data: <memory at 0x000000001B41B348>
itemsize: 4
---------nparr:------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
size: 15
shape: (3, 5)
ndim: 2
dtype: int32
data: <memory at 0x000000001B412558>
itemsize: 4


In [26]:
b = a.reshape((3, 5))
print("b:", b)
print("slice b[1,2] :\t", b[1, 2])
print("slice b[1] :\t", b[1])
print("slice b[2, 3:4] :\t", b[2, 3:4])

b: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
slice b[1,2] :	 7
slice b[1] :	 [5 6 7 8 9]
slice b[2, 3:4] :	 [13]


In [48]:
preds = np.random.random((2, 10))
label = np.random.randint(0, 2, size=C.shape)
print("preds:", preds)
print("preds>0.5:\t",  preds>0.5)
print("label:", label)

print("(preds > 0.5) & (label == 1):", (preds > 0.5) & (label == 1))
c1 = preds[(preds > 0.5) & (label == 1)]
c2 = preds[(preds > 0.5)]
print("c1 = preds[(preds > 0.5) & (label == 1)]:", c1)
print("c2")
print("准确率:", c1.size/c2.size )

preds: [[0.53635087 0.58673538 0.11809069 0.96433765 0.79700007 0.86838959
  0.9964803  0.04766908 0.09578306 0.0469729 ]
 [0.81801932 0.11706574 0.51987015 0.50161447 0.57244913 0.21255622
  0.06278315 0.61826027 0.49267425 0.74024623]]
preds>0.5:	 [[ True  True False  True  True  True  True False False False]
 [ True False  True  True  True False False  True False  True]]
label: [[1 1 0 0 0 0 1 1 1 0]
 [1 0 0 0 0 0 0 1 0 1]]
(preds > 0.5) & (label == 1): [[ True  True False False False False  True False False False]
 [ True False False False False False False  True False  True]]
c1 = preds[(preds > 0.5) & (label == 1)]: [0.53635087 0.58673538 0.9964803  0.81801932 0.61826027 0.74024623]
准确率: 0.5


In [51]:
preds = np.random.random((2, 10))
print(preds)
print(np.argmax(preds, 1))

[[0.98604807 0.88045376 0.35545885 0.11389504 0.39940345 0.66327033
  0.46779491 0.84473159 0.39033236 0.24870198]
 [0.9989874  0.05638326 0.06676975 0.63577839 0.69660037 0.79307086
  0.93731982 0.98474955 0.77789023 0.00821051]]
[0 0]
