In [2]:
import tensorflow as tf


## tf.clip_by_value
tf.clip_by_value(
    t,
    clip_value_min,
    clip_value_max,
    name=None
)
给定的tensor t中的所有值限定在clip_value_min 和 clip_value_max之间

In [17]:
with tf.Graph().as_default():
    tensor_ab = tf.random_normal((3, 4), mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
    after_clip_a = tf.clip_by_value(tensor_ab, 0, 1)
    with tf.Session() as sess:
        output_ab, output_clip = sess.run([tensor_ab, after_clip_a])
        print("origin value:", output_ab)
        print("after clip_by_value(t, 0, 1.0):", output_clip)



origin value: [[-0.27354655 -1.3089035   0.3579834   1.6660101 ]
 [-0.37126926 -0.46291596 -2.008697   -1.3827105 ]
 [-0.6242001  -0.2117389  -1.2942055  -1.9149228 ]]
after clip_by_value(t, 0, 1.0): [[0.        0.        0.3579834 1.       ]
 [0.        0.        0.        0.       ]
 [0.        0.        0.        0.       ]]


## tf.clip_by_global_norm
tf.clip_by_global_norm(
    t_list,
    clip_norm,
    use_norm=None,
    name=None
)

对t_list中的值进行限定，缩小一定尺度(自己理解)
输出的list_clipped计算如下：t_list[i] * clip_norm / max(global_norm, clip_norm)

参数：
use_norm----如果预先已经计算了 global_norm， 可以通过这个参数指定
返回值：
list_clipped: 和t_list保持相同类型的 tensor list
global_norm: global norm的标量

In [39]:
with tf.Graph().as_default():
    tensor_a1 = tf.random_normal((3, 4), mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
    tensor_a2 = tf.random_normal((3, 4), mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
    tensor_norm = tf.constant(2, dtype=tf.float32)
    after_clip_a, global_norm = tf.clip_by_global_norm([tensor_a1, tensor_a2], 1, use_norm=tensor_norm)
    after_clip_a_2, global_norm_2 = tf.clip_by_global_norm([tensor_a1, tensor_a2], 1)
    with tf.Session() as sess:
        output_ab, output_a2, clip_list, global_norm, clip_list_2, global_norm_2 = sess.run([tensor_a1, tensor_a2, after_clip_a, 
                                                                 global_norm, after_clip_a_2, global_norm_2])
        print("origin value a1:\n", output_ab)
        print("origin value a2:\n", output_a2)
        print("after clip_by_global_norm(t, 0, 1.0):\n", clip_list)
        print("global norm:\n\t", global_norm)
        print("------------------------------")
        
        print("origin value a1:\n", output_ab)
        print("origin value a2:\n", output_a2)
        print("after clip_by_global_norm(t, 0, 1.0):\n", clip_list_2)
        print("global norm:\n\t", global_norm_2)

    

origin value a1:
 [[ 0.2801796   1.261506   -0.08506524  1.9679066 ]
 [ 1.3015199  -0.02672353 -0.21450634  0.42450377]
 [-0.92664397 -0.11236522 -1.1519778   0.10334326]]
origin value a2:
 [[ 0.4130754   0.64810586  2.023332   -0.4650102 ]
 [ 0.18793212 -2.3923392   0.00366899  0.10036173]
 [-0.830722   -0.6703147  -0.5850104  -0.6789748 ]]
after clip_by_global_norm(t, 0, 1.0):
 [array([[ 0.1400898 ,  0.630753  , -0.04253262,  0.9839533 ],
       [ 0.65075994, -0.01336176, -0.10725317,  0.21225189],
       [-0.46332198, -0.05618261, -0.5759889 ,  0.05167163]],
      dtype=float32), array([[ 0.2065377 ,  0.32405293,  1.011666  , -0.2325051 ],
       [ 0.09396606, -1.1961696 ,  0.0018345 ,  0.05018086],
       [-0.415361  , -0.33515736, -0.2925052 , -0.3394874 ]],
      dtype=float32)]
global norm:
	 2.0
------------------------------
origin value a1:
 [[ 0.2801796   1.261506   -0.08506524  1.9679066 ]
 [ 1.3015199  -0.02672353 -0.21450634  0.42450377]
 [-0.92664397 -0.11236522 -1.15197

## tf.gradients
tf.gradients(
    ys,
    xs,
    grad_ys=None,
    name='gradients',
    colocate_gradients_with_ops=False,
    gate_gradients=False,
    aggregation_method=None,
    stop_gradients=None
)
计算ys相对于xs的梯度，
参数：
    ys和xs: 需要求导的目标， 是一个tersor或者一个tensor的list
   grad_ys: ys的导数，（用于链式求导）
   stop_gradients： 部分偏导求导，(只计算一次，）不链式传播
    

In [68]:
with tf.Graph().as_default():
    a = tf.constant(0.)
    b = 2.0 * a - 1.0
    c = a + b 
    g = tf.gradients(c , [a, b] )
    g_2 = tf.gradients(c , [a, b], grad_ys = tf.constant(3.0) )
    g_3 = tf.gradients(2* a + 3 * c , [a, c] )
    g_4 = tf.gradients(2* a + 3 * c , [a, c], stop_gradients=[ a, c] )
    with tf.Session() as sess:
        cc, gg, gg2, gg3, gg4 = sess.run([c, g, g_2, g_3, g_4])
        print(cc)
        print("tf.gradients (c=a + b)", gg)
        print("tf.gradients (c=a + b) with grad_ys=3:", gg2)
        print("tf.gradients (2*a + 3 * c) with respect to [a, c]  :", gg3)
        print("tf.gradients (2*a + 3 * c) with respect to [a, c]  with stop_gradients=[ a, c]:", gg4)
        

-1.0
tf.gradients (c=a + b) [3.0, 1.0]
tf.gradients (c=a + b) with grad_ys=3: [9.0, 3.0]
tf.gradients (2*a + 3 * c) with respect to [a, c]  : [11.0, 3.0]
tf.gradients (2*a + 3 * c) with respect to [a, c]  with stop_gradients=[ a, c]: [2.0, 3.0]


## tf.trainable_variables
tf.trainable_variables(scope=None)
参数:
    scope: 指定作用域内
返回值：
    返回所有trainable=True的变量